### ISSUE TITLE
When searching for a channel and typing an 'a' -> Redirected to authentication page

### ISSUE THREAD

**Issue by MaximilianSoerenPollak** [zigzter/chatterm#2] opened 2024-02-11 21:38 UTC
Hey there, 

just had some small dable with the Project looks cool. 

I just found a small bug, that when I'm authenticated etc. and I go to search for a live channel (via 'i') and then when I type the letter 'a' (even after some other letters first) it jumps back to the authentication view.

I had a short look into the source code but could in my brief view not figure out where the bug lies. 

I'm guessing it must have to do with that you give the 'authentication' keystroke priority in some of the case statements, but not quite sure. 

If you need more information let me know.

Keep up the great work.

**Comment by zigzter** [comment] 2024-02-15 17:53
I had a similar issue with the C key, so I'm pretty sure I know what the issue is. I will take a look soon.

Thanks for reporting this!

**Comment by LostinTimeandspaceYT** [comment] 2024-02-17 19:03
Hey @zigzter, Awesome work so far.
I encountered the same bug when typing `a`, but also experienced a similar issue when typing `r` and `i`, strangely, `h` and `l` were fine. 

I played around a bit with `models/channelinput.go` and changed ln 51 from
```go
Auth:    key.NewBinding(key.WithKeys("a"), key.WithHelp("a", "open auth")),
```
to
```go
Auth:    key.NewBinding(key.WithKeys("ctrl+a"), key.WithHelp("ctrl+a", "open auth")),
```
solved the problem with `a`, but attempting to change `i` or `r` to `ctrl+i` and `ctrl+r` respectively had no effect.

Copy pasting the channel name worked fine.

**Comment by zigzter** [comment] 2024-02-18 20:23
@LostinTimeandspaceYT thanks!

Originally I had the bindings under Ctrl keys, but I swapped them to non-Ctrl shortcuts since someone pointed out the Ctrl key tends to be pretty loaded in terminals. I believe that's also why using they `key.NewBinding()` with Ctrl prefixes sometimes doesn't work.

I think if I might need to conditionally add hotkeys, if that's possible. Unfortunately I'm currently pretty occupied with preparing for some interviews, but I'll look into it soon.

**Comment by zigzter** [comment] 2024-02-23 22:48
@MaximilianSoerenPollak  @LostinTimeandspaceYT should be fixed now!

**Closed** 2024-02-23 22:47 UTC
Labels: bug
